/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'men' : IDL.Null,
  'accessories' : IDL.Null,
  'kids' : IDL.Null,
  'women' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockQuantity' : IDL.Nat,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'category' : Category,
  'priceCents' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'size' : IDL.Text,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'items' : IDL.Vec(CartItem),
  'totalPrice' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'addToCart' : IDL.Func([CartItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByUser' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSampleProducts' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([], [IDL.Nat], []),
  'removeFromCart' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'men' : IDL.Null,
    'accessories' : IDL.Null,
    'kids' : IDL.Null,
    'women' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockQuantity' : IDL.Nat,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'category' : Category,
    'priceCents' : IDL.Nat,
  });
  const CartItem = IDL.Record({
    'size' : IDL.Text,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'items' : IDL.Vec(CartItem),
    'totalPrice' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'addToCart' : IDL.Func([CartItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByUser' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSampleProducts' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([], [IDL.Nat], []),
    'removeFromCart' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };